# Generated by Django 2.1 on 2020-01-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200131_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
